controller_joint_names: ['', 'steer1_joint', 'drive1_joint', 'steer2_joint', 'drive2_joint', 'steer3_joint', 'drive3_joint', 'steer4_joint', 'drive4_joint', 'yaw_joint', 'link1_joint', 'link2_joint', 'link3_joint', 'wrist_joint', ]
